{{- if eq .Values.WHITEBOARD_ENABLED "yes" }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: nextcloud-aio-whiteboard
  name: nextcloud-aio-whiteboard
  namespace: "{{ .Values.NAMESPACE }}"
spec:
  ipFamilyPolicy: PreferDualStack
  ports:
    - name: "3002"
      port: 3002
      targetPort: 3002
  selector:
    io.kompose.service: nextcloud-aio-whiteboard
{{- end }}
