{{- if eq .Values.TALK_RECORDING_ENABLED "yes" }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: nextcloud-aio-talk-recording
  name: nextcloud-aio-talk-recording
  namespace: "{{ .Values.NAMESPACE }}"
spec:
  ipFamilyPolicy: PreferDualStack
  ports:
    - name: "1234"
      port: 1234
      targetPort: 1234
  selector:
    io.kompose.service: nextcloud-aio-talk-recording
{{- end }}
